name: "Test Bluetooth HFP/HSP"
version: "1.0.0"
slug: "bluetooth_test"
description: "Tentative de gestion du microphone Bluetooth via PulseAudio"
arch:
  - aarch64  # Pour Raspberry Pi 5
init: false
host_network: false
host_dbus: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
devices:
  - /dev/snd:/dev/snd:rwm
  - /dev/vchiq:/dev/vchiq:rwm # Important pour l'audio sur Raspberry Pi
ports:
  4713/tcp: 4713
volumes:
  - /run/dbus:/run/dbus:ro  # Connexion au DBus de l'hôte
  - /var/run/bluetooth:/var/run/bluetooth:ro # Connexion à Bluetooth de l'hôte